server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

spring:
  application:
    name: msc-zuul-depart

zuul:
  routes:
    # 指定zuul路由规则
    # *为通配符
    # /** 可以匹配0到多级路径
    # /* 只能匹配一级路径
    # /? 只能匹配一级路径，且路径只能包含一个字符
    msc-consumer-depart-8880: /abc8880/**
    msc-consumer-depart-8890: /abc8890/**
    msc-consumer-depart: /abc123/**
  # 屏蔽微服务名称
#  ignored-services:  msc-consumer-depart-8880
  # 屏蔽所有微服务名称
  ignored-services: "*"
  # 指定统一的前缀
  prefix: /abc
  # 屏蔽指定的URI
  ignored-patterns: /**/list/**
  # 屏蔽掉指定的敏感头信息，其会将原来默认的敏感头信息放开
  sensitive-headers: token