server:
  port: 8880

spring:
  application:
    name: msc-consumer-depart

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

#msc-provider-depart:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule