server:
  port: 8880

spring:
  application:
    name: msc-consumer-depart
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
