server:
  port: 8880

spring:
  application:
    name: msc-consumer-depart
  # 指定Zipkin服务器地址
  zipkin:
    base-url: http://localhost:9411/
  # 设置采样比例为1.0，即全部都需要，默认0.1
  sleuth:
    sampler:
      probability: 1.0
  # 指定当前Sleuth要连接的kafka集群
  kafka:
    bootstrap-servers: 120.24.170.213:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

