spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache?serverTimezone=UTC&useSSL=false
    username: root
    password: xiaoBAO22
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: dockerOS1

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.sunbc.cache.mapper: debug