server:
  port: 8881

spring:
  #\u914D\u7F6Espring data jpa
  jpa:
    #\u6307\u5B9A\u662F\u5426\u5728spring\u5BB9\u5668\u542F\u52A8\u662F\u521B\u5EFA\u8868\uFF0C\u9ED8\u8BA4\u662Ffalse
    generate-ddl: true
    #\u6307\u5B9A\u5728\u63A7\u5236\u53F0\u662F\u5426\u663E\u793ASQL\u8BED\u53E5\uFF0C\u9ED8\u8BA4false
    show-sql: true
    #\u6307\u5B9A\u5E94\u7528\u91CD\u542F\u540E\u4E0D\u91CD\u65B0\u66F4\u65B0\u8868\u5185\u5BB9
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: xiaoBAO22


#\u914D\u7F6E\u65E5\u5FD7
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    #\u5728show-sql\u4E3Atrue\u662F\u663E\u793ASQL\u4E2D\u7684\u52A8\u6001\u53C2\u6570\u503C
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #\u5728show-sql\u4E3Atrue\u662F\u663E\u793A\u67E5\u8BE2\u7ED3\u679C
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.sunbc: debug
